import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Check, CreditCard, Crown, Gauge, Loader2, ShieldAlert, Sparkles, Users } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const euro = (cents = 0) => new Intl.NumberFormat('pt-PT', { style: 'currency', currency: 'EUR' }).format(Number(cents || 0) / 100);

export default function BillingPage() {
  const [billing, setBilling] = useState(null); const [plans, setPlans] = useState([]); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async () => { setError(''); const [b,p]=await Promise.all([supabase.rpc('get_my_billing'),supabase.rpc('get_billing_plans')]); if(b.error)throw b.error;if(p.error)throw p.error;setBilling(b.data);setPlans(p.data||[]); };
  useEffect(()=>{load().catch(e=>setError(e.message||'Não foi possível carregar o faturamento.'));},[]);
  const changePlan = async (planCode) => { setBusy(planCode);setError('');try{const {data,error:fnError}=await supabase.functions.invoke('billing-change-plan',{body:{plan_code:planCode}});if(fnError)throw fnError;if(data?.url){window.location.assign(data.url);return;}await load();}catch(e){setError(e.message||'Não foi possível alterar o plano.');}finally{setBusy('');} };
  const usage=useMemo(()=>Math.min(100,Number(billing?.usage_percent||0)),[billing]);
  if(!billing)return <div className="tc-card tc-loading"><Loader2 className="spin"/> A carregar faturamento…</div>;
  return <section className="tc-billing"><div className="tc-page-heading"><div><div className="tc-eyebrow"><CreditCard size={14}/> Faturamento</div><h1>Plano e licenças</h1><p>Controle o crescimento da sua equipa sem sair do Teconnect.</p></div></div>{error&&<div className="tc-error"><ShieldAlert size={16}/> {error}</div>}{(billing.status==='past_due'||billing.billing_blocked)&&<div className="tc-billing-warning"><ShieldAlert size={18}/><div><strong>Atenção ao estado da assinatura</strong><span>Atualize o pagamento ou faça upgrade para manter a operação sem bloqueios.</span></div></div>}<div className="tc-billing-grid"><article className="tc-card tc-plan-card"><div className="tc-plan-icon"><Crown size={20}/></div><span className="tc-muted">Plano atual</span><h2>{billing.plan_name}</h2><strong>{euro(billing.monthly_price_cents)}<small>/mês</small></strong><div className="tc-status">{billing.status}</div><div className="tc-plan-meta"><span>Renovação</span><strong>{billing.renewal_at?new Date(billing.renewal_at).toLocaleDateString('pt-PT'):'—'}</strong></div></article><article className="tc-card"><div className="tc-card-head"><div><span className="tc-muted">Licenças</span><h2>{billing.active_employees} / {billing.max_employees}</h2></div><Users size={20}/></div><div className="tc-progress"><span style={{width:`${usage}%`}}/></div><div className="tc-usage"><span>{usage}% utilizado</span><strong>{Math.max(0,billing.max_employees-billing.active_employees)} disponíveis</strong></div></article></div><div className="tc-section-title"><div><h2>Planos</h2><span>Expanda quando a equipa crescer.</span></div><Sparkles size={18}/></div><div className="tc-plans">{plans.map(plan=>{const current=plan.code===billing.plan_code;return <article key={plan.id} className={`tc-card tc-pricing ${current?'current':''}`}><div className="tc-pricing-top"><h3>{plan.name}</h3>{current&&<span>Atual</span>}</div><div className="tc-price">{euro(plan.monthly_price_cents)}<small>/mês</small></div><div className="tc-license"><Gauge size={15}/> Até {plan.max_employees.toLocaleString('pt-PT')} colaboradores</div><ul>{Object.entries(plan.features||{}).filter(([,enabled])=>enabled).map(([key])=><li key={key}><Check size={14}/> {key==='erp'?'Integrações ERP':key==='advanced_shifts'?'Turnos avançados':key==='predictive_alerts'?'Alertas preditivos':key==='tasks'?'Tarefas RH':key==='sso'?'SSO corporativo':key}</li>)}</ul>{!current&&<button className="tc-btn primary" disabled={!!busy} onClick={()=>changePlan(plan.code)}>{busy===plan.code?<Loader2 className="spin" size={15}/>:<ArrowUpRight size={15}/>} Fazer upgrade</button>}</article>})}</div></section>;
}
