import { useEffect, useState } from 'react';
import { Building2, CheckCircle2, CreditCard, Loader2, Shield, Users, XCircle } from 'lucide-react';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);
const euro = (cents = 0) => new Intl.NumberFormat('pt-PT', { style: 'currency', currency: 'EUR' }).format(Number(cents || 0) / 100);

export default function SuperAdminPage() {
  const [overview, setOverview] = useState(null); const [companies, setCompanies] = useState([]); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const load = async () => { const [o,c] = await Promise.all([supabase.rpc('get_saas_admin_overview'), supabase.rpc('list_saas_companies')]); if (o.error) throw o.error; if (c.error) throw c.error; setOverview(o.data); setCompanies(c.data || []); };
  useEffect(() => { load().catch((e) => setError(e.message || 'Sem permissão ou falha de leitura.')); }, []);
  const setPlan = async (companyId, code, status) => { setBusy(companyId); try { const { error } = await supabase.rpc('super_admin_set_subscription', { p_company_id: companyId, p_plan_code: code, p_status: status }); if (error) throw error; await load(); } catch(e) { setError(e.message || 'Não foi possível alterar a assinatura.'); } finally { setBusy(''); } };
  if (!overview) return <div className="tc-card tc-loading"><Loader2 className="spin" /> A carregar painel SaaS…</div>;
  return <section className="tc-admin"><div className="tc-page-heading"><div><div className="tc-eyebrow"><Shield size={14}/> Super Admin</div><h1>Comando comercial</h1><p>Clientes, receita recorrente e estado das subscrições.</p></div></div>{error && <div className="tc-error">{error}</div>}<div className="tc-admin-stats"><Stat icon={CreditCard} label="MRR" value={euro(overview.mrr_cents)} /><Stat icon={Building2} label="Clientes" value={overview.companies} /><Stat icon={CheckCircle2} label="Pagantes" value={overview.paying} /><Stat icon={Users} label="Colaboradores" value={overview.active_employees} /></div><div className="tc-card tc-table-card"><div className="tc-section-title"><div><h2>Empresas</h2><span>Gestão centralizada de planos e limites.</span></div></div><div className="tc-table-wrap"><table className="tc-table"><thead><tr><th>Empresa</th><th>Plano</th><th>Estado</th><th>Licenças</th><th>MRR</th><th>Ação</th></tr></thead><tbody>{companies.map((c) => <tr key={c.company_id}><td><strong>{c.company_name}</strong><small>{c.nif || '—'}</small></td><td>{c.plan_name || 'Sem plano'}</td><td><span className={`tc-status ${c.status}`}>{c.status || '—'}</span></td><td>{c.active_employees} / {c.max_employees || '—'}</td><td>{euro(c.monthly_price_cents)}</td><td><select disabled={busy === c.company_id} value={c.plan_code || 'STARTER'} onChange={(e) => setPlan(c.company_id,e.target.value,c.status === 'canceled' ? 'active' : (c.status || 'active'))}><option>STARTER</option><option>BUSINESS</option><option>ENTERPRISE</option></select>{c.status === 'active' ? <button className="tc-icon-btn danger" title="Cancelar" onClick={() => setPlan(c.company_id,c.plan_code || 'STARTER','canceled')}><XCircle size={16}/></button> : <button className="tc-icon-btn" title="Ativar" onClick={() => setPlan(c.company_id,c.plan_code || 'STARTER','active')}><CheckCircle2 size={16}/></button>}</td></tr>)}</tbody></table></div></div></section>;
}
function Stat({ icon: Icon, label, value }) { return <div className="tc-card tc-admin-stat"><Icon size={18}/><span>{label}</span><strong>{value}</strong></div>; }
