import { createClient } from '@supabase/supabase-js';
const encoder=new TextEncoder(); const db=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
async function hmac(secret:string,message:string){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,encoder.encode(message));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function equal(a:string,b:string){if(a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0;}
async function valid(payload:string,header:string,secret:string){const parts=Object.fromEntries(header.split(',').map(x=>x.split('=')));const expected=await hmac(secret,`${parts.t}.${payload}`);return !!parts.t&&!!parts.v1&&equal(expected,parts.v1)&&Math.abs(Date.now()/1000-Number(parts.t))<300;}
Deno.serve(async(req)=>{if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});try{const payload=await req.text(),secret=Deno.env.get('STRIPE_WEBHOOK_SECRET'),sig=req.headers.get('stripe-signature')||'';if(!secret||!(await valid(payload,sig,secret)))return new Response('Invalid signature',{status:400});const event=JSON.parse(payload),obj=event.data?.object||{},supa=db(),companyId=obj.metadata?.company_id||obj.client_reference_id;
if(event.type==='checkout.session.completed'&&companyId&&obj.subscription){const subId=typeof obj.subscription==='string'?obj.subscription:obj.subscription.id;const customerId=typeof obj.customer==='string'?obj.customer:obj.customer?.id;const code=String(obj.metadata?.plan_code||'STARTER').toUpperCase();const {data:plan}=await supa.from('subscription_plans').select('id,max_employees').eq('code',code).single();if(plan)await supa.from('subscriptions').upsert({company_id:companyId,plan_id:plan.id,status:'active',max_employees:plan.max_employees,stripe_customer_id:customerId,stripe_subscription_id:subId,stripe_checkout_session_id:obj.id,updated_at:new Date().toISOString()},{onConflict:'company_id'});}
if(event.type.startsWith('customer.subscription.')){const subId=obj.id,company=obj.metadata?.company_id,priceId=obj.items?.data?.[0]?.price?.id;const status=obj.status==='trialing'?'trial':obj.status==='active'?'active':obj.status==='past_due'?'past_due':obj.status==='canceled'?'canceled':obj.status==='paused'?'paused':'incomplete';const {data:plan}=priceId?await supa.from('subscription_plans').select('id,max_employees').eq('stripe_price_id',priceId).maybeSingle():{data:null};const patch:any={status,current_period_start:obj.current_period_start?new Date(obj.current_period_start*1000).toISOString():null,current_period_end:obj.current_period_end?new Date(obj.current_period_end*1000).toISOString():null,renewal_at:obj.current_period_end?new Date(obj.current_period_end*1000).toISOString():null,cancel_at_period_end:!!obj.cancel_at_period_end,canceled_at:obj.canceled_at?new Date(obj.canceled_at*1000).toISOString():null,updated_at:new Date().toISOString()};if(plan){patch.plan_id=plan.id;patch.max_employees=plan.max_employees;}await (company?supa.from('subscriptions').update(patch).eq('company_id',company):supa.from('subscriptions').update(patch).eq('stripe_subscription_id',subId));}
if(event.type==='invoice.payment_failed'){const id=typeof obj.subscription==='string'?obj.subscription:obj.subscription?.id;if(id)await supa.from('subscriptions').update({status:'past_due',updated_at:new Date().toISOString()}).eq('stripe_subscription_id',id);}if(event.type==='invoice.paid'){const id=typeof obj.subscription==='string'?obj.subscription:obj.subscription?.id;if(id)await supa.from('subscriptions').update({status:'active',updated_at:new Date().toISOString()}).eq('stripe_subscription_id',id);}return new Response(JSON.stringify({received:true}),{status:200,headers:{'Content-Type':'application/json'}});}catch(e){console.error(e);return new Response('Webhook error',{status:500});}});
